
package VentanasInterfaz;

import Ventanas.Reportesemanal;
import Ventanas.Tickets;
import Ventanas.Usuarios;
import Ventanas.Consultaproductos;
import Ventanas.Registro;
import Ventanas.actualizar;
import VentanasInterfaz.Login;
import javax.swing.JInternalFrame;

public class Interfaz extends javax.swing.JFrame {

    Registro r;
    Tickets t;
    Usuarios u;

    Reportesemanal rs;
    Consultaproductos cs;
    actualizar ac;
    public static String user;
    public static String pwd;

    /**
     * Creates new form frmPapa
     */
    public Interfaz(String userl, String pwdl) {
        initComponents();
        this.setExtendedState(Interfaz.MAXIMIZED_BOTH);

        this.setTitle("PAPELERIA DEL TEC ");
        this.user = userl;
        this.pwd = pwdl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuRegistro = new javax.swing.JMenuItem();
        Mnuconsulta = new javax.swing.JMenuItem();
        Mnuactualiza = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        copyMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        MnuCusuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuVenta = new javax.swing.JMenuItem();
        mnuTickets = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        MnuRsemanal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAPELERIA DEL TEC");

        fileMenu.setMnemonic('f');
        fileMenu.setText("PRODUCTOS");

        mnuRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        mnuRegistro.setMnemonic('o');
        mnuRegistro.setText("ALTA DE PRODUCTOS");
        mnuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroActionPerformed(evt);
            }
        });
        fileMenu.add(mnuRegistro);

        Mnuconsulta.setText("CONSULTAR PRODUCTOS");
        Mnuconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuconsultaActionPerformed(evt);
            }
        });
        fileMenu.add(Mnuconsulta);

        Mnuactualiza.setText("ACTUALIZAR PRECIOS");
        Mnuactualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuactualizaActionPerformed(evt);
            }
        });
        fileMenu.add(Mnuactualiza);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("PROOVEDOR");

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("PROOVEDORES");
        editMenu.add(copyMenuItem);

        jMenuItem4.setText("REGISTRO PROOVEDOR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem4);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("PERSONAL");

        MnuCusuarios.setText("ALTA DE PERSONAL");
        MnuCusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCusuariosActionPerformed(evt);
            }
        });
        helpMenu.add(MnuCusuarios);

        menuBar.add(helpMenu);

        jMenu1.setText("VENTAS");

        mnuVenta.setMnemonic('c');
        mnuVenta.setText("PUNTO DE VENTA");
        mnuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVenta);

        mnuTickets.setText("TICKETS");
        mnuTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTicketsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTickets);

        menuBar.add(jMenu1);

        jMenu2.setText("REPORTES");

        jMenuItem6.setText("REPORTE DE PROOVEDORES");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        MnuRsemanal.setText("REPORTE SEMANAL ");
        MnuRsemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuRsemanalActionPerformed(evt);
            }
        });
        jMenu2.add(MnuRsemanal);

        menuBar.add(jMenu2);

        jMenu3.setText("SALIR");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("SALIR");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(exitMenuItem);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroActionPerformed
        if (!(r instanceof Registro)) {// si no existe
            r = new Registro();//lo creamos
        }
        CentrarHijas(r);// centramos la hija en el mdi
    }//GEN-LAST:event_mnuRegistroActionPerformed

    private void MnuconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuconsultaActionPerformed
        if (!(cs instanceof Consultaproductos)) {// si no existe
            cs = new Consultaproductos();//lo creamos
        }
        CentrarHijas(cs);// centramos la hija en el mdi
    }//GEN-LAST:event_MnuconsultaActionPerformed

    private void MnuCusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCusuariosActionPerformed
        if (!(u instanceof Usuarios)) {// si no existe
            u = new Usuarios();//lo creamos
        }
        CentrarHijas(u);
    }//GEN-LAST:event_MnuCusuariosActionPerformed

    private void mnuTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTicketsActionPerformed
        if (!(t instanceof Tickets)) {// si no existe
            t = new Tickets();//lo creamos
        }
        CentrarHijas(t);// centramos la hija en el mdi
    }//GEN-LAST:event_mnuTicketsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void MnuRsemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuRsemanalActionPerformed
        if (!(rs instanceof Reportesemanal)) {// si no existe
            rs = new Reportesemanal();//lo creamos
        }
        CentrarHijas(rs);// centramos la hija en el mdi
    }//GEN-LAST:event_MnuRsemanalActionPerformed

    private void MnuactualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuactualizaActionPerformed
        if (!(ac instanceof actualizar)) {// si no existe
            ac = new actualizar();//lo creamos
        }
        CentrarHijas(ac);// centramos la hija en el mdi
    }//GEN-LAST:event_MnuactualizaActionPerformed

    private void mnuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVentaActionPerformed

    void CentrarHijas(JInternalFrame hija) {
        int ancho = (panel.getWidth() / 2) - hija.getWidth() / 2;
        int alto = (panel.getHeight() / 2) - hija.getWidth() / 2;
        if (hija.isShowing()) {// si se muestra
            hija.setLocation(ancho, alto);//la centramos
        } else {
            panel.add(hija);
            hija.setLocation(ancho, alto + 200);

            hija.show();//mostramos
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz(user, pwd).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuCusuarios;
    private javax.swing.JMenuItem MnuRsemanal;
    private javax.swing.JMenuItem Mnuactualiza;
    private javax.swing.JMenuItem Mnuconsulta;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuRegistro;
    private javax.swing.JMenuItem mnuTickets;
    private javax.swing.JMenuItem mnuVenta;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables

}
